########################################################################
################		BuildingUtil Config File		################
#########------------------------------------------------------#########
################	Plugin by: thijmen321 & bramhaag	################
########################################################################

#Automatically place blocks in selected item slot in hotbar if the player has any left in his inventory when he runs out
replace-blocks: true

#Automatically place tools in selected item slot in hotbar if the player has any left in his inventory when a tool breaks
replace-tools: true
